### ISSUE TITLE
Draw Buttons from Scratch

### ISSUE THREAD

**Issue by syl3n7** [syl3n7/MicroMacro-2D#2]

**Comment by Mariana041** [comment]
![Image](https://user-images.githubusercontent.com/100358775/209567679-2ddaaa7c-f680-44c7-9c5f-8bbad4f8bfb5.png)

**Comment by Mariana041** [comment]
![Image](https://user-images.githubusercontent.com/100358775/209575859-e1b89bef-7608-4145-82da-845594294157.png)
![Image](https://user-images.githubusercontent.com/100358775/209575857-07dacd98-eb4d-4b38-8c73-557ab53da3b2.png)
![Image](https://user-images.githubusercontent.com/100358775/209575865-1068ace0-3872-4a71-908a-876b455c212a.png)
![Image](https://user-images.githubusercontent.com/100358775/209575867-838247b0-2886-435f-8f07-ae18af421fa6.png)
![Image](https://user-images.githubusercontent.com/100358775/209575866-3ae43099-7f22-46a8-9c9e-d8df2ffeeebf.png)
![Image](https://user-images.githubusercontent.com/100358775/209575858-e0fc67da-db6f-435c-b8e1-94ba2abbaac5.png)
![Image](https://user-images.githubusercontent.com/100358775/209575870-f6964006-7dd0-4387-b793-ed1f16be5641.png)
![Image](https://user-images.githubusercontent.com/100358775/209575860-35868fd4-58da-4a44-985a-2639429b8414.png)
![Image](https://user-images.githubusercontent.com/100358775/209575861-c1f525d8-f7a1-4baf-9a36-4a0db8e9cd20.png)
![Image](https://user-images.githubusercontent.com/100358775/209575863-c53a3841-cfac-4a5b-bc98-e07f59a86b59.png)
![Image](https://user-images.githubusercontent.com/100358775/209575862-968b7340-3174-42ed-93d9-a8879c5f4c5a.png)
![Image](https://user-images.githubusercontent.com/100358775/209575869-52e0c13a-ce3f-4955-ae99-ba39ed453370.png)
![Image](https://user-images.githubusercontent.com/100358775/209575872-899a513f-ac23-486c-a0d0-a5eebdf2eb5c.png)
![Image](https://user-images.githubusercontent.com/100358775/209575877-fb6b646d-1770-4e99-b15d-9441abedb9a7.png)
![Image](https://user-images.githubusercontent.com/100358775/209575876-1caf768c-2093-4603-8595-8393053cdd09.png)
![Image](https://user-images.githubusercontent.com/100358775/209575868-525b77ca-884a-4280-8097-2b6b3c89ca04.png)
![Image](https://user-images.githubusercontent.com/100358775/209575873-aa33dcfa-e6fc-49a6-a5cc-6e018fcf8cef.png)
![Image](https://user-images.githubusercontent.com/100358775/209575864-befdd119-2d0c-461f-a976-ff161fabbcf5.png)
![Image](https://user-images.githubusercontent.com/100358775/209575875-41cdc9f9-f17c-4acf-b827-2d318e668464.png)
![Image](https://user-images.githubusercontent.com/100358775/209575871-574a5ceb-44a1-4f37-80f6-d8f844a5f353.png)
![Image](https://user-images.githubusercontent.com/100358775/209575881-18ffbb25-50c5-41ee-923b-05a81388e67c.png)
![Image](https://user-images.githubusercontent.com/100358775/209575878-9b4b2f8b-02a5-43a0-861d-21352348a8d6.png)
![Image](https://user-images.githubusercontent.com/100358775/209575880-b3e1e104-f8bb-478e-b6e8-c88d37e33299.png)
![Image](https://user-images.githubusercontent.com/100358775/209575884-ce4f5ca3-3197-4096-a9ff-45fae2f2a6a1.png)
![Image](https://user-images.githubusercontent.com/100358775/209575874-a52f21ca-7641-4306-86a8-b7420a6bae23.png)
![Image](https://user-images.githubusercontent.com/100358775/209575893-21c6bb70-8c5e-404a-aca0-942d03b266ad.png)
![Image](https://user-images.githubusercontent.com/100358775/209575889-bb5baa19-7989-461d-8303-d32fb7eadbd9.png)
![Image](https://user-images.githubusercontent.com/100358775/209575883-d9a0179d-9801-46a7-8378-de758973947c.png)
![Image](https://user-images.githubusercontent.com/100358775/209575885-7079049f-3044-4657-a941-e7e005cb3a91.png)
![Image](https://user-images.githubusercontent.com/100358775/209575886-cc22d5e0-fb90-4343-8c91-2079087411ee.png)
![Image](https://user-images.githubusercontent.com/100358775/209575888-20f9496e-26cf-4fa5-88da-f7c1792074e1.png)
![Image](https://user-images.githubusercontent.com/100358775/209575890-e4191e73-c590-42da-b576-7e537e3b970d.png)
![Image](https://user-images.githubusercontent.com/100358775/209575891-987ab073-c636-4f7e-b37b-5d725ddfcd7b.png)
![Image](https://user-images.githubusercontent.com/100358775/209575879-b3d063b7-fe41-4ecb-b830-0360c5e594af.png)
![Image](https://user-images.githubusercontent.com/100358775/209575894-fa472249-a08d-4c4c-9a66-eb99a97df42a.png)
![Image](https://user-images.githubusercontent.com/100358775/209575887-636787fa-5ae1-4215-8fdb-08404133dcdf.png)
![Image](https://user-images.githubusercontent.com/100358775/209575882-caccbfe7-c865-4714-baba-f4b589c95c1f.png)
![Image](https://user-images.githubusercontent.com/100358775/209575892-325d7f01-2f10-416a-8443-d1715af1d4cc.png)

**Comment by Mariana041** [comment]
![Image](https://user-images.githubusercontent.com/100358775/209575945-54b62e28-0064-41c5-9e51-39bd33442d07.png)

**Comment by syl3n7** [comment]
missing one sprite on the commit.
