### ISSUE TITLE
Bateria

### ISSUE THREAD

**Issue by Mariana041** [syl3n7/MicroMacro-2D#26]

**Comment by syl3n7** [comment]
Concluido

<script src="https://gist.github.com/syl3n7/23eb7a394e1140549e4b0aac01e5b842.js"></script>

**Comment by Mariana041** [comment]
![Image](https://user-images.githubusercontent.com/100358775/212963368-04467fdc-1a0d-46ce-9e7f-1a605b7319f2.png)
![Image](https://user-images.githubusercontent.com/100358775/212963369-5dacbe61-772a-4937-b2da-d6f232fb6a16.png)
![Image](https://user-images.githubusercontent.com/100358775/212963370-63f1b450-ac21-4e27-bb39-6f680f24efc3.png)
